# Company-flavored question bank.
#
# HONESTY NOTE (read this before adding to it): nothing here is claimed to be
# a verified real transcript from an actual interview at these companies. No
# such clean, verifiably-attributed public dataset exists (checked Kaggle and
# HuggingFace directly — see conversation). What DOES genuinely exist and is
# well-documented publicly: each company's interview *culture* and *style* —
# Amazon's published Leadership Principles, Google's structured/data-driven
# problem-solving approach, Meta's execution-speed culture, Apple's design
# and cross-functional-collaboration emphasis, Microsoft's "growth mindset"
# pillar, Netflix's published "Freedom & Responsibility" culture deck. Every
# question below is written to be genuinely representative of that
# documented style, and is used as real grounding material fed to the
# adaptive question generator on EVERY turn (not just the first question),
# so the whole interview stays in that company/domain's flavor while still
# adapting to what the candidate actually says.

COMPANIES = {
    "google": "Google",
    "amazon": "Amazon",
    "meta": "Meta",
    "apple": "Apple",
    "microsoft": "Microsoft",
    "netflix": "Netflix",
}

DOMAINS = {
    "backend": "Backend Engineering",
    "frontend": "Frontend Engineering",
    "data_science": "Data Science",
    "data_analyst": "Data Analyst",
    "ml_engineer": "AI/ML Engineer",
}

# ---------------- BEHAVIORAL (HR + Hiring Manager personas draw from this) ----------------
COMPANY_BEHAVIORAL = {
    "google": [
        "Tell me about a time you had to make a decision with incomplete data. How did you reason through the uncertainty?",
        "Describe a situation where you changed your mind after seeing new evidence. What changed it?",
        "Tell me about a time you disagreed with a team decision. How did you raise it, and what happened?",
        "Give an example of a time you simplified something that was overly complex. What was the impact?",
        "Tell me about a project that failed or fell short. What did you learn, and what did you do differently after?",
        "Describe a time you had to influence someone without having direct authority over them.",
        "Tell me about a time you had to balance moving fast against getting something exactly right.",
        "Give an example of when you took initiative on something outside your formal responsibilities.",
        "Tell me about a time data changed the direction of a project you were on.",
        "Describe how you've handled ambiguous or conflicting priorities on a team.",
        "Tell me about a time you gave difficult feedback to a peer or had to receive it yourself.",
        "Describe a time you had to learn something completely new very quickly to finish a project.",
    ],
    "amazon": [
        "Customer Obsession: Tell me about a time you went out of your way to solve a problem for a customer or user.",
        "Ownership: Describe a time you took on a problem that wasn't technically your responsibility because it needed to get done.",
        "Invent and Simplify: Tell me about a time you simplified a process or solution that others thought was fine as-is.",
        "Bias for Action: Give an example of a time you made a decision quickly with limited information rather than waiting for perfect data.",
        "Frugality: Tell me about a time you accomplished more with less — fewer resources, less budget, or a smaller team than you'd have liked.",
        "Are Right, A Lot: Describe a time your judgment on something was later proven correct despite pushback.",
        "Learn and Be Curious: Tell me about something outside your job that you taught yourself recently, and why.",
        "Insist on the Highest Standards: Describe a time you refused to ship something because it didn't meet your bar, even under time pressure.",
        "Think Big: Tell me about a time you proposed a bigger, bolder solution than what was originally asked for.",
        "Dive Deep: Give an example of a time surface-level data was misleading and you had to dig deeper to find the real cause.",
        "Have Backbone; Disagree and Commit: Tell me about a time you disagreed with a decision, voiced it, and then fully committed once it was made.",
        "Deliver Results: Describe a time you had to push through significant setbacks to deliver on a commitment.",
    ],
    "meta": [
        "Tell me about a time you had to move fast on something with real ambiguity — what did 'good enough to ship' look like?",
        "Describe a time you shipped something imperfect on purpose because speed mattered more than polish in that moment.",
        "Tell me about the most impactful thing you've worked on. How did you measure that impact?",
        "Give an example of a time you had to make a tradeoff between scope and deadline. How did you decide?",
        "Tell me about a time you got real user/customer feedback that changed your approach mid-project.",
        "Describe a time you worked cross-functionally with a team very different from your own to ship something.",
        "Tell me about a time you had to advocate for a user's interest against internal pressure to do otherwise.",
        "Give an example of when being wrong quickly (failing fast) actually helped you.",
        "Tell me about a time you had to communicate a technical decision to a non-technical stakeholder.",
        "Describe how you prioritize when everything on your plate feels urgent.",
    ],
    "apple": [
        "Tell me about a time obsessing over a small detail actually mattered to the outcome.",
        "Describe a project where you had to collaborate closely with a very different discipline (e.g. engineering with design, or design with hardware).",
        "Tell me about a time you pushed back on a design or technical decision because the user experience wasn't right.",
        "Give an example of when you had to keep a project confidential or tightly scoped, and how that affected how you worked.",
        "Describe a time your work had to meet an extremely high quality bar, higher than what felt strictly necessary.",
        "Tell me about a time you simplified a user-facing feature by removing something, not adding to it.",
        "Give an example of a time you iterated many times on something before it felt right.",
        "Tell me about a time you had to say no to a feature request to protect the user's experience.",
    ],
    "microsoft": [
        "Tell me about a time you approached a skill or problem with a growth mindset — where you weren't good at something yet, but got there.",
        "Describe a time you helped a teammate grow or learn something, even if it wasn't part of your job.",
        "Tell me about a time you received critical feedback. How did you respond to it?",
        "Give an example of a time collaboration across teams was hard, and how you worked through it.",
        "Tell me about a time you changed your approach after realizing your first instinct was wrong.",
        "Describe a project where you had to balance innovation with reliability for existing customers.",
        "Tell me about a time you mentored, coached, or supported someone else's growth on a team.",
        "Give an example of a time you had to rebuild trust with a teammate or stakeholder after a mistake.",
    ],
    "netflix": [
        "Tell me about a time you were given a lot of freedom on a project with very little oversight. How did you handle that responsibility?",
        "Describe a time you made a judgment call without asking for permission first, because you believed it was the right call.",
        "Tell me about a time you gave or received very direct, candid feedback. How did it land?",
        "Give an example of a decision you made that prioritized long-term quality over short-term convenience.",
        "Tell me about a time you disagreed strongly with a manager's decision. What did you do?",
        "Describe a time you had to perform at a high level with minimal process or structure around you.",
        "Tell me about a time you chose to end or walk away from a project because it wasn't working, rather than push through.",
        "Give an example of when you had to make a decision that wasn't popular but that you believed was right for the business.",
    ],
}

# ---------------- TECHNICAL (Tech Lead persona draws from this, filtered by domain) ----------------
COMPANY_DOMAIN_TECHNICAL = {
    ("google", "backend"): [
        "How would you design a system to handle search-query autocomplete at very high query volume with low latency?",
        "Walk through how you'd design a rate limiter that needs to work consistently across many servers.",
        "How would you approach reducing p99 latency in a service where the average latency already looks fine?",
        "Design a system for deduplicating a massive, continuously-arriving stream of events.",
        "How would you shard a dataset that's grown too large for a single database, with minimal downtime during the migration?",
        "Walk through your approach to designing an API that needs to stay backward-compatible for years.",
        "How would you design a caching layer for a read-heavy service, and how would you handle cache invalidation?",
        "Describe how you'd debug a service that intermittently times out under production load but never in staging.",
    ],
    ("google", "frontend"): [
        "How would you design a search-results page that needs to render its first result in under 100ms?",
        "Walk through how you'd architect a component library meant to be reused across many different product teams.",
        "How would you debug a memory leak in a long-running single-page application?",
        "Describe your approach to making a data-heavy dashboard accessible to screen-reader users without redesigning it from scratch.",
        "How would you design client-side caching for a page that shows frequently-changing, personalized data?",
        "Walk through how you'd reduce a page's time-to-interactive without removing functionality.",
        "How would you architect state management for a page with many independent, simultaneously-updating widgets?",
        "Describe how you'd approach internationalizing a UI that was originally built assuming left-to-right, English-only text.",
    ],
    ("google", "data_science"): [
        "How would you design an experiment to measure whether a new ranking algorithm actually improves search satisfaction?",
        "Walk through how you'd detect and correct for selection bias in a dataset built from user click logs.",
        "How would you decide between a simpler interpretable model and a more accurate black-box model for a product decision?",
        "Describe how you'd design a metric that resists being gamed once teams start optimizing for it.",
        "How would you approach analyzing a metric that moved, but you're not sure if it's signal or noise?",
        "Walk through how you'd measure long-term user impact when you can only observe short-term data.",
        "How would you handle a data pipeline where upstream data quality silently degrades over time?",
        "Describe your approach to explaining a statistically significant but practically tiny effect to a non-technical stakeholder.",
    ],
    ("google", "data_analyst"): [
        "Walk through how you'd investigate a sudden, unexplained drop in a key metric on a dashboard.",
        "How would you design a dashboard for an executive audience versus one for an engineering team looking at the same underlying data?",
        "Describe how you'd validate that a new data source is trustworthy before building reports on top of it.",
        "How would you approach reconciling two reports that give conflicting numbers for what should be the same metric?",
        "Walk through how you'd write a SQL query to find the most common user path leading to churn.",
        "Describe how you'd handle a stakeholder who wants a specific number without wanting to hear the caveats behind it.",
        "How would you decide which metrics actually belong on a top-level company dashboard versus a team-level one?",
        "Walk through your approach to cleaning a dataset with a mix of missing values, duplicates, and inconsistent formatting.",
    ],
    ("google", "ml_engineer"): [
        "How would you design a training pipeline that needs to retrain a model daily on fresh data without downtime?",
        "Walk through how you'd detect that a deployed model's performance has silently degraded (model drift).",
        "How would you design a feature store shared across multiple ML teams to avoid duplicated feature-engineering work?",
        "Describe your approach to deciding when a model is 'good enough' to ship versus needs more iteration.",
        "How would you design an A/B test to evaluate a new model against the one currently in production?",
        "Walk through how you'd debug a model that performs well offline but poorly once deployed.",
        "How would you approach reducing inference latency for a large model without significantly hurting accuracy?",
        "Describe how you'd design a system for safely rolling back a bad model deployment quickly.",
    ],
    ("amazon", "backend"): [
        "How would you design the backend for a checkout system that must never lose an order, even during a partial outage?",
        "Walk through how you'd design a system to handle a 10x traffic spike during a single day of the year (e.g. a big sale).",
        "How would you design an inventory system where the same item can be sold from multiple warehouses simultaneously without overselling?",
        "Describe how you'd design a retry mechanism for a payment service without risking double-charging customers.",
        "How would you approach designing a service that needs to degrade gracefully rather than fail completely under load?",
        "Walk through how you'd design a queue-based system for processing orders asynchronously at scale.",
        "How would you design a multi-region system so a regional outage doesn't take down the whole service?",
        "Describe how you'd approach cost-optimizing a backend service that's technically working fine but is expensive to run.",
    ],
    ("amazon", "frontend"): [
        "How would you design a product page that needs to load fast even on a slow mobile connection in a market with poor connectivity?",
        "Walk through how you'd build a checkout flow that clearly communicates errors (payment failure, out of stock) without losing the customer.",
        "How would you approach A/B testing a UI change on a high-traffic page with real revenue on the line?",
        "Describe how you'd design a review/ratings widget that scales to millions of items without becoming a performance bottleneck.",
        "How would you handle a UI that needs to work reliably across an enormous range of device and browser combinations?",
        "Walk through how you'd reduce cart-abandonment caused by a slow or confusing checkout page.",
        "How would you design client-side error handling so a failed API call never leaves a customer looking at a broken page?",
        "Describe your approach to testing frontend performance regressions before they reach customers.",
    ],
    ("amazon", "data_science"): [
        "How would you build a model to detect fraudulent transactions while keeping false positives (blocking real customers) low?",
        "Walk through how you'd design a recommendation system for a marketplace with millions of products and sparse purchase history per user.",
        "How would you measure the actual business impact of a recommendation algorithm change, not just its accuracy?",
        "Describe how you'd approach demand forecasting for a product with highly seasonal sales.",
        "How would you decide which customers to prioritize for a limited promotional budget, and how would you validate the approach?",
        "Walk through how you'd handle a model that performs well overall but poorly for a specific customer segment.",
        "Describe your approach to detecting when a change in customer behavior is a trend versus noise.",
        "How would you design an experiment when you can't randomize at the individual customer level (e.g. pricing changes)?",
    ],
    ("amazon", "data_analyst"): [
        "Walk through how you'd analyze why a specific product category's sales suddenly dropped week-over-week.",
        "How would you design a dashboard that tracks delivery performance across multiple warehouses and carriers?",
        "Describe how you'd reconcile inventory numbers that don't match between two internal systems.",
        "How would you approach segmenting customers for a targeted marketing analysis?",
        "Walk through a SQL approach to identifying customers at risk of churning based on order history.",
        "Describe how you'd communicate a negative finding (e.g. a feature is hurting a metric) to the team that built it.",
        "How would you validate that a self-reported metric from a business team is actually accurate before using it?",
        "Walk through how you'd prioritize which of several competing data requests to tackle first.",
    ],
    ("amazon", "ml_engineer"): [
        "How would you design an ML system to personalize product recommendations at checkout in real time?",
        "Walk through how you'd build a pipeline to retrain a fraud-detection model as fraud patterns shift over time.",
        "How would you approach deploying a model to run inference within a strict latency budget during checkout?",
        "Describe how you'd monitor a production model for silent failures that wouldn't show up as a crash.",
        "How would you design the infrastructure to run experiments (A/B tests) on ML model variants safely at scale?",
        "Walk through your approach to feature engineering for a demand-forecasting model with strong seasonality.",
        "How would you handle a situation where your model's training data doesn't reflect current real-world conditions anymore?",
        "Describe how you'd balance model accuracy against the cost of running it at Amazon's scale.",
    ],
    ("meta", "backend"): [
        "How would you design a backend service to support real-time notifications for billions of users?",
        "Walk through how you'd design a news-feed ranking backend that needs to serve personalized results with low latency.",
        "How would you design a messaging system that guarantees message ordering between two users even under network issues?",
        "Describe how you'd approach scaling a service that's suddenly gone viral overnight.",
        "How would you design a system for storing and quickly retrieving a social graph (who's connected to whom)?",
        "Walk through how you'd design rate limiting for an API that's shared across many internal teams.",
        "How would you approach making a backend service resilient to a downstream dependency being slow or down?",
        "Describe your approach to rolling out a risky backend change to a fraction of users first.",
    ],
    ("meta", "frontend"): [
        "How would you design a news feed's rendering so scrolling stays smooth even with rich, varied content types?",
        "Walk through how you'd build a real-time comment section that updates live without janky re-renders.",
        "How would you approach building a UI component that needs to work identically across web and multiple app platforms?",
        "Describe how you'd debug a UI that feels sluggish on lower-end phones but fine on flagship devices.",
        "How would you design a feed's infinite-scroll to avoid loading more data than the user will actually see?",
        "Walk through your approach to feature-flagging a risky frontend change so it can be rolled back instantly.",
        "How would you approach optimizing image/video loading for a feed with a huge amount of visual content?",
        "Describe how you'd design for accessibility in a highly visual, animation-heavy interface.",
    ],
    ("meta", "data_science"): [
        "How would you measure whether a change to the news feed ranking algorithm actually improves user wellbeing, not just engagement?",
        "Walk through how you'd design an experiment when the effect you're testing might take weeks to show up.",
        "How would you approach a metric that's improving in aggregate but might be masking harm to a subgroup of users?",
        "Describe your approach to distinguishing correlation from causation in observational social-network data.",
        "How would you measure the ripple effects of a feature change across a connected social graph, not just individual users?",
        "Walk through how you'd design a holdout group for a feature that's likely to become the new norm quickly.",
        "How would you approach analyzing engagement data that's heavily skewed by a small number of very active users?",
        "Describe how you'd detect novelty effects (a metric improving just because it's new) versus a genuinely better feature.",
    ],
    ("meta", "data_analyst"): [
        "Walk through how you'd investigate whether a drop in daily active users is a real trend or a data pipeline issue.",
        "How would you design a dashboard tracking content-moderation metrics for both accuracy and speed?",
        "Describe how you'd analyze which content types drive the most meaningful engagement versus just time-on-app.",
        "How would you approach an analysis where the underlying user population itself is changing over time?",
        "Walk through a SQL approach to finding which features correlate most with long-term user retention.",
        "Describe how you'd communicate a metric decline to a product team without triggering a knee-jerk overreaction.",
        "How would you validate a self-reported survey metric against actual behavioral data?",
        "Walk through how you'd prioritize competing analytics requests from multiple product teams.",
    ],
    ("meta", "ml_engineer"): [
        "How would you design the ML system behind a feed-ranking model that needs to update its understanding of user interest in near real time?",
        "Walk through how you'd handle a ranking model that's inadvertently amplifying low-quality content.",
        "How would you approach training a model on a dataset that changes distribution rapidly (e.g. trending topics)?",
        "Describe your approach to running many simultaneous model experiments without them interfering with each other.",
        "How would you design monitoring to catch a ranking model degrading for a specific demographic before it becomes a bigger issue?",
        "Walk through how you'd reduce a recommendation model's serving cost at Meta's scale without hurting relevance much.",
        "How would you approach a cold-start problem for a brand-new user with no engagement history?",
        "Describe how you'd balance short-term engagement signals against long-term user satisfaction in a ranking model's objective.",
    ],
    ("apple", "backend"): [
        "How would you design a backend for syncing user data across many devices with strong data-privacy requirements?",
        "Walk through how you'd design a service that must work reliably even when a user's device is intermittently offline.",
        "How would you approach designing a backend to support a major product launch day with a massive, predictable traffic spike?",
        "Describe how you'd design a system where user data needs to be end-to-end encrypted, limiting what your own backend can see.",
        "How would you design conflict resolution for data edited on two devices while offline, then synced later?",
        "Walk through your approach to versioning an API that many different hardware generations depend on simultaneously.",
        "How would you design a backend to minimize battery/network impact on the client device?",
        "Describe how you'd approach a backend outage that specifically affects one product line during a launch window.",
    ],
    ("apple", "frontend"): [
        "How would you approach building a UI feature that needs to feel identically polished across very different screen sizes?",
        "Walk through how you'd optimize animations so they stay smooth without draining battery.",
        "How would you approach a design requirement that conflicts with a technical performance constraint?",
        "Describe your process for iterating on a UI detail (spacing, motion, transition) until it 'feels right.'",
        "How would you design an interface to be fully usable with accessibility features (VoiceOver, larger text) without a separate codepath?",
        "Walk through how you'd approach a feature that needs to work perfectly offline, with no server dependency.",
        "How would you reduce a UI's memory footprint on older, lower-spec devices?",
        "Describe how you'd collaborate with a designer who wants something that's technically very difficult to implement well.",
    ],
    ("apple", "data_science"): [
        "How would you measure feature quality when you deliberately can't collect much user data, for privacy reasons?",
        "Walk through how you'd design an experiment using on-device, privacy-preserving analytics instead of raw user data.",
        "How would you approach evaluating a feature's success using only aggregated, anonymized signals?",
        "Describe your approach to a data science problem where you have very limited sample size due to privacy constraints.",
        "How would you validate a model's fairness across different device types and user demographics with limited data access?",
        "Walk through how you'd detect a data quality issue when you can't inspect individual user records directly.",
        "How would you approach forecasting demand for a new hardware product with no direct historical precedent?",
        "Describe how you'd communicate an ambiguous result to a product team that wants a clear yes/no answer.",
    ],
    ("apple", "data_analyst"): [
        "Walk through how you'd build a dashboard for hardware sales performance across different regions and retail channels.",
        "How would you analyze customer support data to identify a hardware defect before it becomes a bigger recall issue?",
        "Describe how you'd approach an analysis where most of your data must stay aggregated for privacy reasons.",
        "How would you validate a metric coming from an on-device, privacy-preserving collection method?",
        "Walk through a SQL approach to comparing product performance across different hardware generations.",
        "Describe how you'd communicate a data-driven recommendation to a design-led team that prioritizes intuition.",
        "How would you approach reconciling retail sales data with online sales data that use different definitions?",
        "Walk through how you'd prioritize dashboard requests from multiple hardware and software teams.",
    ],
    ("apple", "ml_engineer"): [
        "How would you design an on-device ML model given strict constraints on memory, compute, and battery life?",
        "Walk through how you'd approach training a model when you can't centrally collect the raw training data (federated/privacy-preserving learning).",
        "How would you evaluate a model's accuracy when you can't directly inspect the data it's making predictions on?",
        "Describe your approach to compressing a large model to run efficiently on a phone-class device.",
        "How would you design a system to update an on-device model without requiring a full app update?",
        "Walk through how you'd debug a model that behaves differently across different hardware chip generations.",
        "How would you approach a model that needs to work with zero network connectivity?",
        "Describe how you'd balance model accuracy against strict latency requirements for a real-time on-device feature.",
    ],
    ("microsoft", "backend"): [
        "How would you design a backend service that needs to serve both a consumer product and an enterprise product with different SLAs?",
        "Walk through how you'd design multi-tenant architecture so one enterprise customer's load can't degrade another's experience.",
        "How would you approach designing a service migration from on-premise to cloud with zero downtime for customers?",
        "Describe how you'd design an API that needs to support both a modern and a decade-old legacy enterprise client.",
        "How would you design a backend system to meet strict enterprise compliance/audit-logging requirements?",
        "Walk through your approach to designing a service with configurable retention policies per enterprise customer.",
        "How would you design for graceful degradation when a customer's specific integration is misbehaving?",
        "Describe how you'd approach capacity planning for a service with very different usage patterns across global enterprise customers.",
    ],
    ("microsoft", "frontend"): [
        "How would you design a UI component library meant to be themeable and reused across many different enterprise products?",
        "Walk through how you'd approach frontend accessibility given Microsoft's enterprise customers include government and public-sector clients with strict compliance needs.",
        "How would you design a UI that needs to work well for both mouse/keyboard and touch, often on the same device?",
        "Describe how you'd approach performance for a productivity app that keeps documents open and syncing for hours at a time.",
        "How would you design collaborative, real-time multi-user editing (like co-authoring a document) on the frontend?",
        "Walk through how you'd handle a UI feature request that conflicts with an existing enterprise customer's workflow.",
        "How would you approach localizing a complex enterprise UI for dozens of languages and locales?",
        "Describe your approach to migrating a legacy UI incrementally without disrupting existing enterprise users.",
    ],
    ("microsoft", "data_science"): [
        "How would you measure productivity-tool feature adoption across enterprise customers with very different org sizes?",
        "Walk through how you'd design an experiment for an enterprise product where you can't randomize at the individual-user level.",
        "How would you approach a churn-prediction model for enterprise customers, where a single 'customer' is really an entire organization?",
        "Describe how you'd evaluate a feature's success when your primary users (IT admins) differ from your primary usage data (end employees).",
        "How would you handle analyzing usage data that spans wildly different company sizes and industries?",
        "Walk through your approach to a metric that needs to be reported differently to enterprise customers versus internal teams.",
        "How would you approach detecting anomalous usage that could indicate either a bug or a security issue?",
        "Describe how you'd communicate a data science finding to enterprise customers who need certainty, not probabilities.",
    ],
    ("microsoft", "data_analyst"): [
        "Walk through how you'd build a dashboard tracking enterprise customer health (usage, support tickets, renewal risk).",
        "How would you analyze which product features actually drive enterprise contract renewals?",
        "Describe how you'd reconcile usage data reported by different products within the same suite.",
        "How would you approach an analysis where enterprise customers self-report data of varying quality?",
        "Walk through a SQL approach to identifying enterprise accounts at risk of downgrading their subscription.",
        "Describe how you'd present a data-driven finding to an enterprise sales team focused on relationships, not metrics.",
        "How would you validate that a support-ticket dataset accurately reflects real customer pain points?",
        "Walk through how you'd prioritize dashboard requests across product, sales, and support teams.",
    ],
    ("microsoft", "ml_engineer"): [
        "How would you design an ML feature that needs to run consistently across cloud and on-premise enterprise deployments?",
        "Walk through how you'd approach a model that must meet enterprise data-residency and compliance requirements.",
        "How would you design a training pipeline for a model that's fine-tuned per enterprise customer without data leaking between them?",
        "Describe your approach to monitoring a model deployed into environments you don't have direct visibility into (customer-hosted).",
        "How would you approach explainability requirements for an ML feature used in a regulated enterprise context?",
        "Walk through how you'd handle versioning a model that enterprise customers depend on for their own workflows.",
        "How would you design a fallback for when an ML feature isn't available in a customer's specific deployment environment?",
        "Describe how you'd balance innovation speed against the stability enterprise customers expect from Microsoft products.",
    ],
    ("netflix", "backend"): [
        "How would you design a backend to handle a massive, predictable traffic spike the moment a hit show releases?",
        "Walk through how you'd design a content-delivery system to minimize buffering for users on varying internet speeds globally.",
        "How would you approach designing a service with no formal process, where you're expected to make architecture calls independently?",
        "Describe how you'd design a system that needs to stay highly available even if an entire cloud region fails (Netflix runs chaos engineering for exactly this).",
        "How would you design a backend for personalized content delivery that varies by region due to licensing?",
        "Walk through your approach to designing a service where you're solely accountable for its reliability, with minimal oversight.",
        "How would you approach a service handling encoding/transcoding video at massive scale cost-efficiently?",
        "Describe how you'd design for quick, independent rollback if a backend change causes issues in production.",
    ],
    ("netflix", "frontend"): [
        "How would you design a UI that needs to feel instant and smooth on both a high-end smart TV and a low-end streaming stick?",
        "Walk through how you'd approach A/B testing a UI change directly on production with real, high-stakes user impact.",
        "How would you design content thumbnails/previews to load fast without overwhelming bandwidth-constrained users?",
        "Describe how you'd handle a frontend bug that specifically affects one class of device (e.g. a specific smart TV model).",
        "How would you approach building a UI with total ownership and freedom, with no formal design-review gate?",
        "Walk through your approach to personalizing UI layout per user without hurting page load performance.",
        "How would you design offline-download functionality for a primarily streaming-based product?",
        "Describe how you'd measure whether a UI change actually improved the viewing experience, not just engagement.",
    ],
    ("netflix", "data_science"): [
        "How would you measure whether a change to the recommendation algorithm actually improves long-term viewer satisfaction, not just clicks?",
        "Walk through how you'd design an experiment when you have full autonomy to decide the methodology yourself, with no fixed process.",
        "How would you approach a content-investment decision (what to greenlight) using data, given inherently uncertain outcomes?",
        "Describe how you'd measure the true incremental value of a specific title to subscriber retention.",
        "How would you handle analyzing viewing data that's heavily skewed by a few extremely popular titles?",
        "Walk through your approach to detecting when a personalization algorithm is creating too narrow a content bubble for users.",
        "How would you approach a churn-prediction model where the actual 'churn' event (cancellation) is relatively rare?",
        "Describe how you'd present a data-driven recommendation you're confident in, knowing you're expected to just make the call yourself.",
    ],
    ("netflix", "data_analyst"): [
        "Walk through how you'd build a dashboard tracking viewer engagement and churn risk in near real time.",
        "How would you analyze whether a new UI layout change is helping or hurting content discovery?",
        "Describe how you'd reconcile viewing-hours data across different device types and regions.",
        "How would you approach an analysis where you're expected to make the final call yourself, with no committee sign-off?",
        "Walk through a SQL approach to identifying which content genres drive the most subscriber retention.",
        "Describe how you'd communicate a finding that contradicts a popular internal assumption about viewer behavior.",
        "How would you validate that regional viewing data accurately reflects licensing and catalog differences?",
        "Walk through how you'd prioritize your own analytics roadmap given minimal top-down direction.",
    ],
    ("netflix", "ml_engineer"): [
        "How would you design the recommendation system's serving infrastructure to personalize the homepage for every user in real time?",
        "Walk through how you'd approach a model that needs to balance content diversity against pure engagement optimization.",
        "How would you design an experimentation platform to let many teams run independent ML experiments without central sign-off?",
        "Describe your approach to monitoring a recommendation model for a sudden drop in relevance after a catalog change.",
        "How would you design a cold-start recommendation approach for a brand-new subscriber with no viewing history?",
        "Walk through how you'd take full ownership of a model's production reliability with minimal formal process around you.",
        "How would you approach a model that performs well globally but poorly for a specific region's content catalog?",
        "Describe how you'd balance model complexity against the operational cost of running it across Netflix's global scale.",
    ],
}


def get_behavioral_pool(company: str) -> list:
    return COMPANY_BEHAVIORAL.get(company, [])


def get_technical_pool(company: str, domain: str) -> list:
    return COMPANY_DOMAIN_TECHNICAL.get((company, domain), [])
