# A bundled bank of DSA practice questions for the Practice page.
#
# Why bundled instead of pulling live from Kaggle/HuggingFace: this backend
# has to run offline on a judge's/teammate's laptop during a hackathon demo —
# a live dataset download is one more thing that can fail at the worst moment
# (network, auth, rate limits, schema drift). This bank is ~90 real, commonly
# asked DSA questions (far more than the old 12), each tagged with difficulty
# and topic so the Practice page's difficulty buttons have real data to filter
# on. Problem text is authored in English only; the /dsa/question endpoint
# translates it into Hindi/Kannada on request (and caches the translation in
# memory) instead of maintaining 3 hand-translated copies of the bank.
#
# id format: <topic>-<n>, difficulty is one of: easy | medium | hard

DSA_QUESTIONS = [
    # ---------------- EASY ----------------
    {"id": "arr-1", "topic": "arrays", "difficulty": "easy",
     "title": "Two Sum",
     "prompt": "Given an array of integers and a target value, return the indices of the two numbers that add up to the target. Assume exactly one solution exists.",
     "examples": ["Input: nums=[2,7,11,15], target=9 -> Output: [0,1]"]},
    {"id": "arr-2", "topic": "arrays", "difficulty": "easy",
     "title": "Reverse an Array In Place",
     "prompt": "Given an array, reverse it in place without using extra space for another array.",
     "examples": ["Input: [1,2,3,4] -> Output: [4,3,2,1]"]},
    {"id": "arr-3", "topic": "arrays", "difficulty": "easy",
     "title": "Find the Maximum Subarray Sum (Kadane's, easy version)",
     "prompt": "Given an array of integers, find the contiguous subarray with the largest sum and return that sum.",
     "examples": ["Input: [-2,1,-3,4,-1,2,1,-5,4] -> Output: 6 (subarray [4,-1,2,1])"]},
    {"id": "arr-4", "topic": "arrays", "difficulty": "easy",
     "title": "Move Zeroes",
     "prompt": "Given an array, move all zeroes to the end while keeping the relative order of non-zero elements, in place.",
     "examples": ["Input: [0,1,0,3,12] -> Output: [1,3,12,0,0]"]},
    {"id": "arr-5", "topic": "arrays", "difficulty": "easy",
     "title": "Find the Missing Number",
     "prompt": "Given an array containing n distinct numbers taken from 0..n, find the one number missing from the range.",
     "examples": ["Input: [3,0,1] -> Output: 2"]},
    {"id": "str-1", "topic": "strings", "difficulty": "easy",
     "title": "Valid Palindrome",
     "prompt": "Given a string, check if it is a palindrome after converting to lowercase and removing non-alphanumeric characters.",
     "examples": ["Input: 'A man, a plan, a canal: Panama' -> Output: true"]},
    {"id": "str-2", "topic": "strings", "difficulty": "easy",
     "title": "First Non-Repeating Character",
     "prompt": "Given a string, return the index of the first character that does not repeat. Return -1 if none.",
     "examples": ["Input: 'leetcode' -> Output: 0"]},
    {"id": "str-3", "topic": "strings", "difficulty": "easy",
     "title": "Valid Anagram",
     "prompt": "Given two strings, determine if one is an anagram of the other.",
     "examples": ["Input: s='anagram', t='nagaram' -> Output: true"]},
    {"id": "str-4", "topic": "strings", "difficulty": "easy",
     "title": "Reverse Words in a Sentence",
     "prompt": "Given a sentence, reverse the order of the words (not the letters within each word).",
     "examples": ["Input: 'the sky is blue' -> Output: 'blue is sky the'"]},
    {"id": "str-5", "topic": "strings", "difficulty": "easy",
     "title": "Count Vowels and Consonants",
     "prompt": "Given a string, count the number of vowels and consonants in it.",
     "examples": ["Input: 'hello world' -> Output: vowels=3, consonants=7"]},
    {"id": "ll-1", "topic": "linked-list", "difficulty": "easy",
     "title": "Reverse a Linked List",
     "prompt": "Given the head of a singly linked list, reverse it and return the new head.",
     "examples": ["Input: 1->2->3->None -> Output: 3->2->1->None"]},
    {"id": "ll-2", "topic": "linked-list", "difficulty": "easy",
     "title": "Middle of a Linked List",
     "prompt": "Given the head of a singly linked list, return the middle node. If there are two middle nodes, return the second one.",
     "examples": ["Input: 1->2->3->4->5 -> Output: node with value 3"]},
    {"id": "ll-3", "topic": "linked-list", "difficulty": "easy",
     "title": "Detect a Cycle in a Linked List",
     "prompt": "Given the head of a linked list, determine if the list has a cycle.",
     "examples": ["Input: a list where the tail connects back to node 2 -> Output: true"]},
    {"id": "stack-1", "topic": "stacks-queues", "difficulty": "easy",
     "title": "Valid Parentheses",
     "prompt": "Given a string containing just '()[]{}', determine if the input string is valid (every bracket closes in the right order).",
     "examples": ["Input: '()[]{}' -> Output: true", "Input: '(]' -> Output: false"]},
    {"id": "stack-2", "topic": "stacks-queues", "difficulty": "easy",
     "title": "Implement a Queue Using Two Stacks",
     "prompt": "Implement a first-in-first-out queue using only two stacks, supporting enqueue and dequeue.",
     "examples": ["enqueue(1); enqueue(2); dequeue() -> 1"]},
    {"id": "tree-1", "topic": "trees", "difficulty": "easy",
     "title": "Maximum Depth of a Binary Tree",
     "prompt": "Given the root of a binary tree, return its maximum depth (number of nodes along the longest path from root to leaf).",
     "examples": ["Input: [3,9,20,null,null,15,7] -> Output: 3"]},
    {"id": "tree-2", "topic": "trees", "difficulty": "easy",
     "title": "Same Tree",
     "prompt": "Given the roots of two binary trees, check if they are structurally identical with the same node values.",
     "examples": ["Input: p=[1,2,3], q=[1,2,3] -> Output: true"]},
    {"id": "hash-1", "topic": "hashing", "difficulty": "easy",
     "title": "Contains Duplicate",
     "prompt": "Given an array of integers, return true if any value appears at least twice.",
     "examples": ["Input: [1,2,3,1] -> Output: true"]},
    {"id": "hash-2", "topic": "hashing", "difficulty": "easy",
     "title": "Two Arrays Intersection",
     "prompt": "Given two arrays, return their intersection (unique values present in both).",
     "examples": ["Input: [1,2,2,1], [2,2] -> Output: [2]"]},
    {"id": "math-1", "topic": "math", "difficulty": "easy",
     "title": "FizzBuzz",
     "prompt": "Print numbers 1 to n, but for multiples of 3 print 'Fizz', for multiples of 5 print 'Buzz', for multiples of both print 'FizzBuzz'.",
     "examples": ["Input: n=5 -> Output: 1,2,Fizz,4,Buzz"]},
    {"id": "math-2", "topic": "math", "difficulty": "easy",
     "title": "Check if a Number is Prime",
     "prompt": "Given an integer, determine whether it is a prime number.",
     "examples": ["Input: 17 -> Output: true"]},
    {"id": "bs-1", "topic": "binary-search", "difficulty": "easy",
     "title": "Binary Search",
     "prompt": "Given a sorted array and a target, return its index using binary search, or -1 if not found.",
     "examples": ["Input: nums=[-1,0,3,5,9,12], target=9 -> Output: 4"]},
    {"id": "recur-1", "topic": "recursion", "difficulty": "easy",
     "title": "Factorial",
     "prompt": "Write a recursive function to compute the factorial of a non-negative integer n.",
     "examples": ["Input: n=5 -> Output: 120"]},
    {"id": "recur-2", "topic": "recursion", "difficulty": "easy",
     "title": "Fibonacci Number",
     "prompt": "Given n, return the n-th Fibonacci number (0-indexed).",
     "examples": ["Input: n=6 -> Output: 8"]},

    # ---------------- MEDIUM ----------------
    {"id": "arr-6", "topic": "arrays", "difficulty": "medium",
     "title": "Product of Array Except Self",
     "prompt": "Given an array nums, return an array where each element is the product of all other elements, without using division and in O(n) time.",
     "examples": ["Input: [1,2,3,4] -> Output: [24,12,8,6]"]},
    {"id": "arr-7", "topic": "arrays", "difficulty": "medium",
     "title": "Rotate a Matrix 90 Degrees In Place",
     "prompt": "Given an n x n matrix, rotate it by 90 degrees clockwise in place.",
     "examples": ["Input: [[1,2],[3,4]] -> Output: [[3,1],[4,2]]"]},
    {"id": "arr-8", "topic": "arrays", "difficulty": "medium",
     "title": "3Sum",
     "prompt": "Given an array of integers, find all unique triplets that sum to zero.",
     "examples": ["Input: [-1,0,1,2,-1,-4] -> Output: [[-1,-1,2],[-1,0,1]]"]},
    {"id": "arr-9", "topic": "arrays", "difficulty": "medium",
     "title": "Merge Intervals",
     "prompt": "Given a list of intervals, merge all overlapping intervals and return the resulting non-overlapping intervals.",
     "examples": ["Input: [[1,3],[2,6],[8,10]] -> Output: [[1,6],[8,10]]"]},
    {"id": "arr-10", "topic": "arrays", "difficulty": "medium",
     "title": "Find Minimum in Rotated Sorted Array",
     "prompt": "Given a rotated sorted array with no duplicates, find the minimum element in O(log n).",
     "examples": ["Input: [4,5,6,7,0,1,2] -> Output: 0"]},
    {"id": "str-6", "topic": "strings", "difficulty": "medium",
     "title": "Longest Substring Without Repeating Characters",
     "prompt": "Given a string, find the length of the longest substring without repeating characters.",
     "examples": ["Input: 'abcabcbb' -> Output: 3"]},
    {"id": "str-7", "topic": "strings", "difficulty": "medium",
     "title": "Group Anagrams",
     "prompt": "Given an array of strings, group the anagrams together.",
     "examples": ["Input: ['eat','tea','tan','ate','nat','bat'] -> Output: [['eat','tea','ate'],['tan','nat'],['bat']]"]},
    {"id": "str-8", "topic": "strings", "difficulty": "medium",
     "title": "Longest Palindromic Substring",
     "prompt": "Given a string, return the longest palindromic substring.",
     "examples": ["Input: 'babad' -> Output: 'bab' or 'aba'"]},
    {"id": "ll-4", "topic": "linked-list", "difficulty": "medium",
     "title": "Merge Two Sorted Linked Lists",
     "prompt": "Given the heads of two sorted linked lists, merge them into one sorted linked list.",
     "examples": ["Input: 1->2->4, 1->3->4 -> Output: 1->1->2->3->4->4"]},
    {"id": "ll-5", "topic": "linked-list", "difficulty": "medium",
     "title": "Remove the N-th Node From the End of a List",
     "prompt": "Given the head of a linked list, remove the n-th node from the end and return the head, in one pass.",
     "examples": ["Input: [1,2,3,4,5], n=2 -> Output: [1,2,3,5]"]},
    {"id": "tree-3", "topic": "trees", "difficulty": "medium",
     "title": "Validate a Binary Search Tree",
     "prompt": "Given the root of a binary tree, determine if it is a valid binary search tree.",
     "examples": ["Input: [2,1,3] -> Output: true", "Input: [5,1,4,null,null,3,6] -> Output: false"]},
    {"id": "tree-4", "topic": "trees", "difficulty": "medium",
     "title": "Level Order Traversal of a Binary Tree",
     "prompt": "Given the root of a binary tree, return the level-order traversal of its nodes' values (left to right, level by level).",
     "examples": ["Input: [3,9,20,null,null,15,7] -> Output: [[3],[9,20],[15,7]]"]},
    {"id": "tree-5", "topic": "trees", "difficulty": "medium",
     "title": "Lowest Common Ancestor of a Binary Search Tree",
     "prompt": "Given a BST and two nodes, find their lowest common ancestor.",
     "examples": ["Input: root=[6,2,8,0,4,7,9], p=2, q=8 -> Output: 6"]},
    {"id": "graph-1", "topic": "graphs", "difficulty": "medium",
     "title": "Number of Islands",
     "prompt": "Given a 2D grid of '1's (land) and '0's (water), count the number of islands (connected land regions, horizontally or vertically).",
     "examples": ["Input: grid with one connected land blob and one separate cell -> Output: 2"]},
    {"id": "graph-2", "topic": "graphs", "difficulty": "medium",
     "title": "Course Schedule (Detect a Cycle in a Directed Graph)",
     "prompt": "Given a number of courses and a list of prerequisite pairs, determine if it's possible to finish all courses (i.e. no cycle in the dependency graph).",
     "examples": ["Input: numCourses=2, prerequisites=[[1,0]] -> Output: true"]},
    {"id": "graph-3", "topic": "graphs", "difficulty": "medium",
     "title": "Clone a Graph",
     "prompt": "Given a reference to a node in a connected undirected graph, return a deep copy (clone) of the graph.",
     "examples": ["Input: adjList=[[2,4],[1,3],[2,4],[1,3]] -> Output: a structurally identical cloned graph"]},
    {"id": "heap-1", "topic": "heaps", "difficulty": "medium",
     "title": "Kth Largest Element in an Array",
     "prompt": "Given an integer array and an integer k, return the k-th largest element.",
     "examples": ["Input: [3,2,1,5,6,4], k=2 -> Output: 5"]},
    {"id": "heap-2", "topic": "heaps", "difficulty": "medium",
     "title": "Top K Frequent Elements",
     "prompt": "Given an integer array and an integer k, return the k most frequent elements.",
     "examples": ["Input: [1,1,1,2,2,3], k=2 -> Output: [1,2]"]},
    {"id": "dp-1", "topic": "dynamic-programming", "difficulty": "medium",
     "title": "Climbing Stairs",
     "prompt": "You are climbing a staircase of n steps. Each time you can climb 1 or 2 steps. In how many distinct ways can you reach the top?",
     "examples": ["Input: n=3 -> Output: 3"]},
    {"id": "dp-2", "topic": "dynamic-programming", "difficulty": "medium",
     "title": "Coin Change (Minimum Coins)",
     "prompt": "Given coin denominations and a target amount, return the fewest number of coins needed to make that amount, or -1 if impossible.",
     "examples": ["Input: coins=[1,2,5], amount=11 -> Output: 3 (5+5+1)"]},
    {"id": "dp-3", "topic": "dynamic-programming", "difficulty": "medium",
     "title": "Longest Increasing Subsequence",
     "prompt": "Given an integer array, find the length of the longest strictly increasing subsequence.",
     "examples": ["Input: [10,9,2,5,3,7,101,18] -> Output: 4"]},
    {"id": "dp-4", "topic": "dynamic-programming", "difficulty": "medium",
     "title": "House Robber",
     "prompt": "Given an array of amounts stored in houses in a row, find the max amount you can rob without robbing two adjacent houses.",
     "examples": ["Input: [1,2,3,1] -> Output: 4"]},
    {"id": "back-1", "topic": "backtracking", "difficulty": "medium",
     "title": "Generate Parentheses",
     "prompt": "Given n pairs of parentheses, generate all combinations of well-formed parentheses.",
     "examples": ["Input: n=3 -> Output: ['((()))','(()())','(())()','()(())','()()()']"]},
    {"id": "back-2", "topic": "backtracking", "difficulty": "medium",
     "title": "Subsets",
     "prompt": "Given an array of unique integers, return all possible subsets (the power set).",
     "examples": ["Input: [1,2,3] -> Output: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"]},
    {"id": "sw-1", "topic": "sliding-window", "difficulty": "medium",
     "title": "Minimum Size Subarray Sum",
     "prompt": "Given an array of positive integers and a target sum, find the minimal length of a contiguous subarray whose sum is >= target.",
     "examples": ["Input: target=7, nums=[2,3,1,2,4,3] -> Output: 2 ([4,3])"]},
    {"id": "sw-2", "topic": "sliding-window", "difficulty": "medium",
     "title": "Longest Repeating Character Replacement",
     "prompt": "Given a string and an integer k, find the length of the longest substring containing the same letter after replacing at most k characters.",
     "examples": ["Input: s='ABAB', k=2 -> Output: 4"]},
    {"id": "twoptr-1", "topic": "two-pointers", "difficulty": "medium",
     "title": "Container With Most Water",
     "prompt": "Given an array of heights, find two lines that together with the x-axis form a container holding the most water.",
     "examples": ["Input: [1,8,6,2,5,4,8,3,7] -> Output: 49"]},

    # ---------------- HARD ----------------
    {"id": "arr-11", "topic": "arrays", "difficulty": "hard",
     "title": "Trapping Rain Water",
     "prompt": "Given n non-negative integers representing an elevation map, compute how much water it can trap after raining.",
     "examples": ["Input: [0,1,0,2,1,0,1,3,2,1,2,1] -> Output: 6"]},
    {"id": "arr-12", "topic": "arrays", "difficulty": "hard",
     "title": "Median of Two Sorted Arrays",
     "prompt": "Given two sorted arrays, find the median of the two combined, in O(log(m+n)) time.",
     "examples": ["Input: [1,3], [2] -> Output: 2.0"]},
    {"id": "arr-13", "topic": "arrays", "difficulty": "hard",
     "title": "First Missing Positive",
     "prompt": "Given an unsorted integer array, find the smallest missing positive integer, in O(n) time and O(1) extra space.",
     "examples": ["Input: [3,4,-1,1] -> Output: 2"]},
    {"id": "str-9", "topic": "strings", "difficulty": "hard",
     "title": "Minimum Window Substring",
     "prompt": "Given two strings s and t, find the minimum window in s which contains all characters of t (including duplicates).",
     "examples": ["Input: s='ADOBECODEBANC', t='ABC' -> Output: 'BANC'"]},
    {"id": "str-10", "topic": "strings", "difficulty": "hard",
     "title": "Regular Expression Matching",
     "prompt": "Implement regular expression matching supporting '.' and '*' with the standard semantics.",
     "examples": ["Input: s='aa', p='a*' -> Output: true"]},
    {"id": "ll-6", "topic": "linked-list", "difficulty": "hard",
     "title": "Merge K Sorted Lists",
     "prompt": "Given an array of k sorted linked lists, merge them into one sorted linked list.",
     "examples": ["Input: [[1,4,5],[1,3,4],[2,6]] -> Output: [1,1,2,3,4,4,5,6]"]},
    {"id": "ll-7", "topic": "linked-list", "difficulty": "hard",
     "title": "Reverse Nodes in k-Group",
     "prompt": "Given a linked list, reverse the nodes k at a time and return the modified list.",
     "examples": ["Input: [1,2,3,4,5], k=2 -> Output: [2,1,4,3,5]"]},
    {"id": "tree-6", "topic": "trees", "difficulty": "hard",
     "title": "Serialize and Deserialize a Binary Tree",
     "prompt": "Design an algorithm to serialize a binary tree to a string and deserialize it back to the original tree.",
     "examples": ["Input: [1,2,3,null,null,4,5] -> serialize then deserialize should reproduce the same tree"]},
    {"id": "tree-7", "topic": "trees", "difficulty": "hard",
     "title": "Binary Tree Maximum Path Sum",
     "prompt": "Given a binary tree, find the maximum path sum where a path is any sequence of nodes connected by edges (need not pass through the root).",
     "examples": ["Input: [-10,9,20,null,null,15,7] -> Output: 42"]},
    {"id": "graph-4", "topic": "graphs", "difficulty": "hard",
     "title": "Word Ladder",
     "prompt": "Given a begin word, an end word, and a dictionary, find the length of the shortest transformation sequence changing one letter at a time, each intermediate word valid.",
     "examples": ["Input: beginWord='hit', endWord='cog', wordList=['hot','dot','dog','lot','log','cog'] -> Output: 5"]},
    {"id": "graph-5", "topic": "graphs", "difficulty": "hard",
     "title": "Alien Dictionary",
     "prompt": "Given a list of words sorted lexicographically by an unknown alien alphabet, derive the order of letters.",
     "examples": ["Input: ['wrt','wrf','er','ett','rftt'] -> Output: 'wertf'"]},
    {"id": "dp-5", "topic": "dynamic-programming", "difficulty": "hard",
     "title": "Edit Distance",
     "prompt": "Given two strings, find the minimum number of insert/delete/replace operations to convert one into the other.",
     "examples": ["Input: word1='horse', word2='ros' -> Output: 3"]},
    {"id": "dp-6", "topic": "dynamic-programming", "difficulty": "hard",
     "title": "Word Break II",
     "prompt": "Given a string and a dictionary of words, return all possible sentences where the string can be segmented into dictionary words.",
     "examples": ["Input: s='catsanddog', wordDict=['cat','cats','and','sand','dog'] -> Output: ['cats and dog','cat sand dog']"]},
    {"id": "dp-7", "topic": "dynamic-programming", "difficulty": "hard",
     "title": "Regular Matrix Chain Multiplication",
     "prompt": "Given dimensions of matrices to be multiplied in sequence, find the minimum number of scalar multiplications needed.",
     "examples": ["Input: dims=[10,20,30,40] -> Output: 18000 (optimal parenthesization)"]},
    {"id": "heap-3", "topic": "heaps", "difficulty": "hard",
     "title": "Find Median from a Data Stream",
     "prompt": "Design a data structure that supports adding numbers one at a time and finding the median of the numbers seen so far, efficiently.",
     "examples": ["addNum(1); addNum(2); findMedian() -> 1.5; addNum(3); findMedian() -> 2"]},
    {"id": "greedy-1", "topic": "greedy", "difficulty": "hard",
     "title": "Job Scheduling to Maximize Profit",
     "prompt": "Given start times, end times, and profits for n jobs, find the maximum profit subset of non-overlapping jobs.",
     "examples": ["Input: jobs with overlapping and non-overlapping windows -> Output: the max achievable non-overlapping profit"]},
    {"id": "trie-1", "topic": "tries", "difficulty": "hard",
     "title": "Implement a Trie with Wildcard Search",
     "prompt": "Design a data structure that supports insert(word) and search(word) where search can include '.' to match any single letter.",
     "examples": ["insert('bad'); search('b.d') -> true"]},
]


def by_difficulty(difficulty: str):
    difficulty = (difficulty or "medium").lower()
    if difficulty in ("moderate",):
        difficulty = "medium"
    if difficulty in ("difficult", "hard"):
        difficulty = "hard"
    pool = [q for q in DSA_QUESTIONS if q["difficulty"] == difficulty]
    return pool or DSA_QUESTIONS


def by_id(question_id: str):
    for q in DSA_QUESTIONS:
        if q["id"] == question_id:
            return q
    return None
